name: MovieDB
options:
  deploymentTarget:
    iOS: $(IPHONEOS_DEPLOYMENT_TARGET)
packages:
  Moya:
    url: https://github.com/Moya/Moya.git
    majorVersion: 15.0.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    majorVersion: 7.0.0
  SkeletonView:
    url: https://github.com/Juanpe/SkeletonView.git
    majorVersion: 1.7.0
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: MovieDB/Config/MovieDBDebug.xcconfig
  Release: MovieDB/Config/MovieDBRelease.xcconfig
settings:
  base:
    # USER DEFINED PROJECT
    BUILD_NUMBER: $(BUILD_NUMBER)
    VERSION_NAME: $(VERSION_NAME)
    CURRENT_PROJECT_VERSION: $(BUILD_NUMBER)
    MARKETING_VERSION: $(VERSION_NAME)
    SDKROOT: iphoneos
    INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
targets:
  MovieDB:
    type: application
    platform: iOS
    sources:
      - path: MovieDB
        name: MovieDB
    dependencies:
      - package: Moya
      - package: Kingfisher
      - package: SkeletonView
    scheme:
      testTargets:
        - MovieDBTests
    settings:
      base:
      # USER DEFINED TARGET
        INFOPLIST_FILE: MovieDB/Info.plist
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          PRODUCT_NAME: $(PRODUCT_NAME)
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
          PRODUCT_NAME: $(PRODUCT_NAME)

  MovieDBTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget:
      iOS: $(IPHONEOS_DEPLOYMENT_TARGET)
    sources:
      - MovieDBTests
    dependencies:
      - target: MovieDB
    settings:
      CODE_SIGN_STYLE: Automatic
      base:
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          PRODUCT_NAME: $(PRODUCT_NAME)
          PRODUCT_MODULE_NAME: $(PRODUCT_NAME)tests
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/$(PRODUCT_NAME)
        Release:
          PRODUCT_NAME: $(PRODUCT_NAME)
          PRODUCT_MODULE_NAME: $(PRODUCT_NAME)tests
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/$(PRODUCT_NAME)

schemes:
  MovieDB: 
    build:
      targets:
        MovieDB: all
        MovieDBTests: [test]
    run:
      config: Debug
    tests:
      config: Debug
      gatherConverageData: true
      coverageTargets:
        - MovieDBTests
      targets:
        - name: MovieDBTests
    profile:
      config: Debug
    analyze:
      config: Debug
    archive: Debug
